version: "3.9"
services:
  postgres:
    image: postgres:11.14-bullseye
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
  pgAdmin:
    image: dpage/pgadmin4:6.4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@email.com
      - PGADMIN_DEFAULT_PASSWORD=1
    ports:
      - "8080:90"
